# 3-dars uchun 2-dataset

In [105]:
import pandas as pd

In [106]:
df=pd.read_csv('Flood_Prediction_NCR_Philippines.csv')

In [107]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7308 entries, 0 to 7307
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              7308 non-null   object
 1   Location          7308 non-null   object
 2   Rainfall_mm       7281 non-null   float64
 3   WaterLevel_m      7134 non-null   float64
 4   SoilMoisture_pct  7282 non-null   float64
 5   Elevation_m       7308 non-null   int64
 6   FloodOccurrence   7308 non-null   int64
dtypes: float64(3), int64(2), object(2)
memory usage: 399.8+ KB

In [108]:
df.isnull().sum()

Date                  0
Location              0
Rainfall_mm          27
WaterLevel_m        174
SoilMoisture_pct     26
Elevation_m           0
FloodOccurrence       0
dtype: int64

In [109]:
from sklearn.preprocessing import LabelEncoder

In [110]:
for col in df.columns:
    encoder=LabelEncoder()
    if df[col].isnull().any():
        df[col].fillna(df[col].mode()[0],inplace=True)

C:\Users\aaa\AppData\Local\Temp\ipykernel_9220\428104347.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0],inplace=True)

In [111]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7308 entries, 0 to 7307
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              7308 non-null   object
 1   Location          7308 non-null   object
 2   Rainfall_mm       7308 non-null   float64
 3   WaterLevel_m      7308 non-null   float64
 4   SoilMoisture_pct  7308 non-null   float64
 5   Elevation_m       7308 non-null   int64
 6   FloodOccurrence   7308 non-null   int64
dtypes: float64(3), int64(2), object(2)
memory usage: 399.8+ KB

# Encoding qilish

In [112]:
df.head()

,Date,Location,Rainfall_mm,WaterLevel_m,SoilMoisture_pct,Elevation_m,FloodOccurrence
0,01/01/2016,Quezon City,12.0,0.5,15.3,43,0
1,01/01/2016,Marikina,10.6,1.8,23.2,15,0
2,01/01/2016,Manila,5.7,0.5,15.6,5,0
3,01/01/2016,Pasig,3.7,0.5,5.0,5,0
4,02/01/2016,Quezon City,3.4,0.5,13.3,43,0

In [113]:
for col in df.columns:
    encoder=LabelEncoder()
    if df[col].dtype=='object':
        df[col]=encoder.fit_transform(df[col])

In [114]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7308 entries, 0 to 7307
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              7308 non-null   int64
 1   Location          7308 non-null   int64
 2   Rainfall_mm       7308 non-null   float64
 3   WaterLevel_m      7308 non-null   float64
 4   SoilMoisture_pct  7308 non-null   float64
 5   Elevation_m       7308 non-null   int64
 6   FloodOccurrence   7308 non-null   int64
dtypes: float64(3), int64(4)
memory usage: 399.8 KB

# Scaling

In [115]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler
minmax=MinMaxScaler()
standard=StandardScaler()
robust=RobustScaler()

In [116]:
num_col=df.columns.drop('FloodOccurrence')
num_robust=['Rainfall_mm','WaterLevel_m','Date']
num_standard=['SoilMoisture_pct','Elevation_m','Location']

In [117]:
#df[num_col]=minmax.fit_transform(df[num_col])
df[num_robust]=robust.fit_transform(df[num_robust])
df[num_standard]=standard.fit_transform(df[num_standard])

In [118]:
df.head(25)

,Date,Location,Rainfall_mm,WaterLevel_m,SoilMoisture_pct,Elevation_m,FloodOccurrence
0,-0.998906,1.341641,0.410557,-0.307692,0.025800,1.671343,0
1,-0.998906,-0.447214,0.246334,0.692308,1.339976,-0.128565,0
2,-0.998906,-1.341641,-0.328446,-0.307692,0.075705,-0.771389,0
3,-0.998906,0.447214,-0.563050,-0.307692,-1.687621,-0.771389,0
4,-0.933260,1.341641,-0.598240,-0.307692,-0.306904,1.671343,0
5,-0.933260,-0.447214,-0.914956,-0.307692,-0.739417,-0.128565,0
6,-0.933260,-1.341641,-0.375367,-0.307692,-0.323539,-0.771389,0
7,-0.933260,0.447214,0.891496,-0.307692,-0.024106,-0.771389,0
8,-0.867615,1.341641,-0.035191,-0.307692,-1.055485,1.671343,0
9,-0.867615,-0.447214,0.304985,-0.307692,0.242056,-0.128565,0
10,-0.867615,-1.341641,-0.715543,-0.307692,-0.489890,-0.771389,0
11,-0.867615,0.447214,0.809384,-0.307692,0.325232,-0.771389,0
12,-0.801969,1.341641,-0.762463,-0.307692,-1.288377,1.671343,0
13,-0.801969,-0.447214,-0.551320,-0.307692,-0.273633,-0.128565,0
14,-0.801969,-1.341641,-0.445748,-0.307692,0.042435,-0.771389,0
15,-0.801969,0.447214,0.821114,-0.307692,-0.256998,-0.771389,0
16,-0.736324,1.341641,0.258065,-0.307692,0.840922,1.671343,0
17,-0.736324,-0.447214,-0.293255,-0.307692,0.325232,-0.128565,0
18,-0.736324,-1.341641,-0.070381,-0.307692,0.641300,-0.771389,0
19,-0.736324,0.447214,0.715543,-0.307692,0.325232,-0.771389,0
20,-0.670678,1.341641,-0.961877,-0.307692,-0.140552,1.671343,0
21,-0.670678,-0.447214,0.997067,0.923077,0.375138,-0.128565,0
22,-0.670678,-1.341641,1.583578,0.846154,0.541489,-0.771389,0
23,-0.670678,0.447214,-0.304985,0.000000,0.391773,-0.771389,0
24,-0.605033,1.341641,-0.363636,0.769231,0.025800,1.671343,0

# Model training

In [119]:
y=df['FloodOccurrence']

In [120]:
x=df.drop('FloodOccurrence',axis=1)

In [121]:
from sklearn.model_selection import train_test_split

In [122]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [123]:
x_train.shape

(5846, 6)

In [124]:
x_test.shape

(1462, 6)

In [125]:
from sklearn.linear_model import LogisticRegression

In [126]:
lr=LogisticRegression()

In [127]:
lr

LogisticRegression()

In [128]:
lr.fit(x_train,y_train)

LogisticRegression()